pigmysql: 
  replicaCount: 1
  images: ccr.ccs.tencentyun.com/pigservice/pig-mysql:8.0.32
  pullPolicy: IfNotPresent
  containerPort: 3306
  service:
    type: "ClusterIP"
    port: 3306
  env:
    - name: MYSQL_ROOT_HOST
      value: '%'
    - name: MYSQL_ROOT_PASSWORD
      value: root
pigredis: 
  replicaCount: 1
  images: ccr.ccs.tencentyun.com/pigservice/redis:7.2.4
  pullPolicy: IfNotPresent
  containerPort: 6379
  service:
    type: "ClusterIP"
    port: 6379
pigregister: 
  domainName: pig-register.idevops.site
  replicaCount: 1
  images: ccr.ccs.tencentyun.com/pigservice/pig-register:RELEASE-1.1.1
  pullPolicy: IfNotPresent
  containerPort: 
    - containerPort: 8848
      protocol: TCP
    - containerPort: 9848
      protocol: TCP
  service:
    type: "ClusterIP"
    port: 
      - name: "web"
        port: 8848
        targetPort: 8848
      - name: "9848"
        port: 9848
        targetPort: 9848
  env:
    - name: MYSQL_USER
      value: 'root'
    - name: MYSQL_PWD
      value: 'root'
    - name: MYSQL_HOST
      value: 'pig-mysql.pigservices.svc.cluster.local'
    - name: MYSQL_PORT
      value: '3306'  
    - name: MYSQL_DB
      value: 'pig_config'
    - name: GATEWAY_HOST
      value: 'pig-gateway.pigservices.svc.cluster.local'
    - name: GATEWAY-PORT
      value: '9999'
    # 从Dockerfile把参数拿出来替换加上skywalking配置
    - name: JAVA_OPTS
      value: "-Xms512m -Xmx8192m  -javaagent:/skywalking-agent/agent/skywalking-agent.jar -Dskywalking.agent.service_name=pig-register -Dskywalking.collector.backend_service=skywalking-oap.skywalking.svc.cluster.local:11800 "
piggateway: 
  domainName: pig-register.idevops.site
  replicaCount: 1
  images: ccr.ccs.tencentyun.com/pigservice/pig-gateway:RELEASE-1.1.1
  pullPolicy: IfNotPresent
  containerPort: 
    - containerPort: 9999
      protocol: TCP
  service:
    type: "ClusterIP"
    port: 
      - name: "web"
        port: 9999
        targetPort: 9999
  env:
    - name: "NACOS_HOST"
      value: 'pig-register.pigservices.svc.cluster.local.'
    - name: "NACOS_PORT"
      value: '8848'
    # 从Dockerfile把参数拿出来替换加上skywalking配置
    - name: JAVA_OPTS
      value: "-Xms512m -Xmx2048m -javaagent:/skywalking-agent/agent/skywalking-agent.jar -Dskywalking.agent.service_name=pig-gateway -Dskywalking.collector.backend_service=skywalking-oap.skywalking.svc.cluster.local:11800 "
pigupms:
  replicaCount: 1
  images: ccr.ccs.tencentyun.com/pigservice/pig-upms:RELEASE-1.1.1
  pullPolicy: IfNotPresent
  containerPort: 
    - containerPort: 4000
      protocol: TCP
  service:
    type: "ClusterIP"
    port: 
      - name: "4000"
        port: 4000
        targetPort: 4000
  env:
    - name: "NACOS_HOST"
      value: 'pig-register.pigservices.svc.cluster.local.'
    - name: "NACOS_PORT"
      value: '8848'
    - name: MYSQL_HOST
      value: 'pig-mysql.pigservices.svc.cluster.local'
    - name: MYSQL_PORT
      value: '3306'  
    - name: MYSQL_DB
      value: 'pig'
    # 从Dockerfile把参数拿出来替换加上skywalking配置
    - name: JAVA_OPTS
      value: "-Xms512m -Xmx1024m -javaagent:/skywalking-agent/agent/skywalking-agent.jar -Dskywalking.agent.service_name=pig-upms -Dskywalking.collector.backend_service=skywalking-oap.skywalking.svc.cluster.local:11800 "
pigmonitor: 
  replicaCount: 1
  images: ccr.ccs.tencentyun.com/pigservice/pig-monitor:RELEASE-1.1.1
  pullPolicy: IfNotPresent
  containerPort: 
    - containerPort: 5001
      protocol: TCP
  service:
    type: "ClusterIP"
    port: 
      - name: "5001"
        port: 5001
        targetPort: 5001
  env:
    - name: "NACOS_HOST"
      value: 'pig-register.pigservices.svc.cluster.local.'
    - name: "NACOS_PORT"
      value: '8848'
    # 从Dockerfile把参数拿出来替换加上skywalking配置
    - name: JAVA_OPTS
      value: "-Xms512m -Xmx1024m -Djava.security.egd=file:/dev/./urandom -javaagent:/skywalking-agent/agent/skywalking-agent.jar -Dskywalking.agent.service_name=pig-monitor -Dskywalking.collector.backend_service=skywalking-oap.skywalking.svc.cluster.local:11800 "
pigcodegen:
  replicaCount: 1
  images: ccr.ccs.tencentyun.com/pigservice/pig-codegen:RELEASE-1.1.1
  pullPolicy: IfNotPresent
  containerPort: 
    - containerPort: 5002
      protocol: TCP
  service:
    type: "ClusterIP"
    port: 
      - name: "5002"
        port: 5002
        targetPort: 5002
  env:
    - name: "NACOS_HOST"
      value: 'pig-register.pigservices.svc.cluster.local.'
    - name: "NACOS_PORT"
      value: '8848'
    - name: MYSQL_HOST
      value: 'pig-mysql.pigservices.svc.cluster.local'
    - name: MYSQL_PORT
      value: '3306'  
    - name: MYSQL_DB
      value: 'pig'
    # 从Dockerfile把参数拿出来替换加上skywalking配置
    - name: JAVA_OPTS
      value: "-Xms512m -Xmx1024m -Djava.security.egd=file:/dev/./urandom -javaagent:/skywalking-agent/agent/skywalking-agent.jar -Dskywalking.agent.service_name=pig-codegen -Dskywalking.collector.backend_service=skywalking-oap.skywalking.svc.cluster.local:11800 "
pigauth:
  replicaCount: 1
  images: ccr.ccs.tencentyun.com/pigservice/pig-auth:RELEASE-1.1.1
  pullPolicy: IfNotPresent
  containerPort: 
    - containerPort: 3000
      protocol: TCP
  service:
    type: "ClusterIP"
    port: 
      - name: "3000"
        port: 3000
        targetPort: 3000
  env:
    - name: "NACOS_HOST"
      value: 'pig-register.pigservices.svc.cluster.local.'
    - name: "NACOS_PORT"
      value: '8848'
    # 从Dockerfile把参数拿出来替换加上skywalking配置
    - name: JAVA_OPTS
      value: "-Xms512m -Xmx1024m -javaagent:/skywalking-agent/agent/skywalking-agent.jar -Dskywalking.agent.service_name=pig-auth -Dskywalking.collector.backend_service=skywalking-oap.skywalking.svc.cluster.local:11800 "
pigquartz:
  replicaCount: 1
  images: ccr.ccs.tencentyun.com/pigservice/pig-quartz:RELEASE-1.1.1
  pullPolicy: IfNotPresent
  containerPort: 
    - containerPort: 5007
      protocol: TCP
  service:
    type: "ClusterIP"
    port: 
      - name: "5007"
        port: 5007
        targetPort: 5007
  env:
    - name: "NACOS_HOST"
      value: 'pig-register.pigservices.svc.cluster.local.'
    - name: "NACOS_PORT"
      value: '8848'
    - name: MYSQL_HOST
      value: 'pig-mysql.pigservices.svc.cluster.local'
    - name: MYSQL_PORT
      value: '3306'  
    - name: MYSQL_DB
      value: 'pig'
    # 从Dockerfile把参数拿出来替换加上skywalking配置
    - name: JAVA_OPTS
      value: "-Xms128m -Xmx256m -Djava.security.egd=file:/dev/./urandom -javaagent:/skywalking-agent/agent/skywalking-agent.jar -Dskywalking.agent.service_name=pig-quartz -Dskywalking.collector.backend_service=skywalking-oap.skywalking.svc.cluster.local:11800 "
pigui: 
  domainName: pig.idevops.site
  replicaCount: 1
  images: ccr.ccs.tencentyun.com/pigservice/pig-ui:RELEASE-1.1.1
  pullPolicy: IfNotPresent
  containerPort: 
    - containerPort: 80
      protocol: TCP
  service:
    type: "ClusterIP"
    port: 
      - name: "web"
        port: 80
        targetPort: 80
initContainers:
  - name: init-skywalking-agent
    image: ccr.ccs.tencentyun.com/devopsvip/skywalking-java-agent:9.2.0-java17
    command: ["sh", "-c", "cp -R /skywalking/agent/ /skywalking-agent; rm -fr /skywalking-agent/agent/plugins"]
    volumeMounts:
      - name: skywalking-agent
        mountPath: /skywalking-agent
volumeMounts:
  - name: skywalking-agent
    mountPath: /skywalking-agent
volumes:
  - name: skywalking-agent
    emptyDir: {}