pigmysql: 
  replicaCount: 1
  images: ccr.ccs.tencentyun.com/pigservice/pig-mysql:8.0.32
  pullPolicy: IfNotPresent
  containerPort: 3306
  service:
    type: "ClusterIP"
    port: 3306
  env:
    - name: MYSQL_ROOT_HOST
      value: '%'
    - name: MYSQL_ROOT_PASSWORD
      value: root
pigredis: 
  replicaCount: 1
  images: ccr.ccs.tencentyun.com/pigservice/redis:7.2.4
  pullPolicy: IfNotPresent
  containerPort: 6379
  service:
    type: "ClusterIP"
    port: 6379
pigregister: 
  replicaCount: 1
  images: ccr.ccs.tencentyun.com/pigservice/pig-register:RELEASE-1.1.1
  pullPolicy: IfNotPresent
  containerPort: 
    - containerPort: 8848
      protocol: TCP
    - containerPort: 9848
      protocol: TCP
  service:
    type: "ClusterIP"
    port: 
      - name: "web"
        port: 8848
        targetPort: 8848
      - name: "9848"
        port: 9848
        targetPort: 9848
  env:
    - name: MYSQL_USER
      value: 'root'
    - name: MYSQL_PWD
      value: 'root'
    - name: MYSQL_HOST
      value: 'pig-mysql.pigservices.svc.cluster.local'
    - name: MYSQL_PORT
      value: '3306'  
    - name: MYSQL_DB
      value: 'pig_config'
    - name: GATEWAY_HOST
      value: 'pig-gateway.pigservices.svc.cluster.local'
    - name: GATEWAY-PORT
      value: '9999'