apiVersion: v1
kind: Service
metadata:
  name: pig-mysql
  labels:
    {{- include "pigmysql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.pigmysql.service.type }}
  ports:
    - port: {{ .Values.pigmysql.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pigmysql.selectorLabels" . | nindent 4 }}
