apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pigredis.fullname" . }}
  labels:
    {{- include "pigredis.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.pigredis.replicaCount }}
  selector:
    matchLabels:
      {{- include "pigredis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pigredis.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.pigredis.images }}"
          ports:
            - name: http
              containerPort: {{ .Values.pigredis.containerPort }}
              protocol: TCP