apiVersion: v1
kind: Service
metadata:
  name: pig-redis
  labels:
    {{- include "pigredis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.pigredis.service.type }}
  ports:
    - port: {{ .Values.pigredis.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pigredis.selectorLabels" . | nindent 4 }}
