apiVersion: apps/v1
kind: Deployment
metadata:
  name: pig-auth
  labels:
    {{- include "pigservices.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.pigauth.replicaCount }}
  selector:
    matchLabels:
      service: pig-auth
  template:
    metadata:
      labels:
       service: pig-auth
    spec:
      {{- if .Values.skywalking.enabled -}}
      initContainers:
        {{- toYaml .Values.initContainers | nindent 8 }}
      {{- end }}
      containers:
        - name: pig-auth
          image: "{{ .Values.pigauth.images }}"
          ports:
            {{- toYaml .Values.pigauth.containerPort | nindent 12 }}
          env:
            {{- toYaml .Values.pigauth.env | nindent 12 }}
          volumeMounts:
            {{- if .Values.skywalking.enabled -}}
            {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}
            volumeMounts:
            - name: piglogs
              mountPath: /var/lib/jenkins
      volumes:
        {{- if .Values.skywalking.enabled -}}
        {{- toYaml .Values.volumes | nindent 8 }} 
        {{- end }}
        - name: piglogs
          persistentVolumeClaim:
            claimName: piglogs
