apiVersion: v1
kind: Service
metadata:
  name: pig-ui
  labels:
    {{- include "pigservices.labels" . | nindent 4 }}
spec:
  type: {{ .Values.pigui.service.type }}
  ports:
    {{- toYaml .Values.pigui.service.port | nindent 4 }}
  selector:
    service: pig-ui
