apiVersion: apps/v1
kind: Deployment
metadata:
  name: pig-gateway
  labels:
    {{- include "pigservices.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.piggateway.replicaCount }}
  selector:
    matchLabels:
      service: pig-gateway
  template:
    metadata:
      labels:
       service: pig-gateway
    spec:
      {{- if .Values.skywalking.enabled -}}
      initContainers:
        {{- toYaml .Values.initContainers | nindent 8 }}
      {{- end }}
      containers:
        - name: pig-gateway
          image: "{{ .Values.piggateway.images }}"
          ports:
            {{- toYaml .Values.piggateway.containerPort | nindent 12 }}
          env:
            {{- if .Values.skywalking.enabled -}}
            # 从Dockerfile把参数拿出来替换加上skywalking配置
            - name: JAVA_OPTS
              value: "-Xms512m -Xmx8192m  -javaagent:/skywalking-agent/agent/skywalking-agent.jar -Dskywalking.agent.service_name=pig-gateway -Dskywalking.collector.backend_service=skywalking-oap.skywalking.svc.cluster.local:11800 "
            {{- end }}
            {{- toYaml .Values.piggateway.env | nindent 12 }}
          volumeMounts:
            {{- if .Values.skywalking.enabled -}}
            {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}
            - name: piglogs
              mountPath: /pig-gateway/logs/
      volumes:
        {{- if .Values.skywalking.enabled -}}
        {{- toYaml .Values.volumes | nindent 8 }} 
        {{- end }}
        - name: piglogs
          persistentVolumeClaim:
            claimName: piglogs

