apiVersion: v1
kind: PersistentVolume
metadata:
  name: piglogs
  labels:
    app: piglogs
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  nfs:
    path: /data/storage/kubernetes/piglogs
    server: 192.168.1.200
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piglogs
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  selector:
    matchLabels:
      app: piglogs