apiVersion: apps/v1
kind: Deployment
metadata:
  name: pig-gateway
  labels:
    {{- include "pigservices.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.piggateway.replicaCount }}
  selector:
    matchLabels:
      service: pig-gateway
  template:
    metadata:
      labels:
       service: pig-gateway
    spec:
      containers:
        - name: pig-gateway
          image: "{{ .Values.piggateway.images }}"
          ports:
            {{- toYaml .Values.piggateway.containerPort | nindent 12 }}
          env:
            {{- toYaml .Values.piggateway.env | nindent 12 }}
