apiVersion: apps/v1
kind: Deployment
metadata:
  name: pig-quartz
  labels:
    {{- include "pigservices.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.pigquartz.replicaCount }}
  selector:
    matchLabels:
      service: pig-quartz
  template:
    metadata:
      labels:
       service: pig-quartz
    spec:
      initContainers:
        {{- toYaml .Values.initContainers | nindent 8 }}
      containers:
        - name: pig-quartz
          image: "{{ .Values.pigquartz.images }}"
          ports:
            {{- toYaml .Values.pigquartz.containerPort | nindent 12 }}
          env:
            {{- toYaml .Values.pigquartz.env | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }} 
