apiVersion: v1
kind: Service
metadata:
  name: pig-codegen
  labels:
    {{- include "pigservices.labels" . | nindent 4 }}
spec:
  type: {{ .Values.pigcodegen.service.type }}
  ports:
    {{- toYaml .Values.pigcodegen.service.port | nindent 4 }}
  selector:
    service: pig-codegen
