apiVersion: v1
kind: Service
metadata:
  name: pig-upms
  labels:
    {{- include "pigservices.labels" . | nindent 4 }}
spec:
  type: {{ .Values.pigupms.service.type }}
  ports:
    {{- toYaml .Values.pigupms.service.port | nindent 4 }}
  selector:
    service: pig-upms
