apiVersion: v1
kind: Service
metadata:
  name: {{ include "pigservices.fullname" . }}
  labels:
    {{- include "pigservices.labels" . | nindent 4 }}
spec:
  type: {{ .Values.pigregister.service.type }}
  ports:
    {{- toYaml .Values.pigregister.port | nindent 4 }}
  selector:
    {{- include "pigservices.selectorLabels" . | nindent 4 }}
